### ISSUE TITLE
Leaves & Saplings Missing Tags

### ISSUE THREAD

**Issue by WenXin20** [joshiejack/Horticulture#3]
`Minecraft v1.16.5`
`Forge v36.1.32`
`Horticulture v1.0.1`

Fruit Tree Leaves are missing the block & item tag `minecraft:leaves` for mod recipe compatibility and for the mod FallingTree to be able to chop down the tree without having to add the fruit leaves to the config manually, since it checks for the block tag first.

Saplings are also missing the block tag `minecraft:saplings`, and the apple sapling is missing it for both the block and item tag.

**Comment by joshiejack** [comment]
Didn't even cross my mind since I don't think they're used in recipes normally? Will add the tags though.

**Comment by WenXin20** [comment]
Yeah, not in vanilla, but datapacks and mods can use the item tags for recipes. And the FallingTree mod use the block tag for leaves. Thanks!
